version: "3.9"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsApi
    expose:
        - "8080"
    ports:
        - "8080:8080"
    depends_on:
      - redis
      - prometheus
      - grafana

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      monitoring:
        aliases:
          - prometheus

  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      monitoring:
        aliases:
          - grafana

networks:
  monitoring: