global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
  - job_name: 'system'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]